### ISSUE TITLE
迭代计划 - 2020年3月 - 前两周（2.25 - 3.09）

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#117]
整体目标: 

1. 船屋点餐APP MVP版本以及流水线搭建。

2.船屋点餐WEB 下单流程MVP版本。

3.全流程流水线包括（单元测试、接口测试、自动化UI测试）

PO: @pipin @elegant1998 @brother-dong @ups216 
维护团队： @zhouwenyang @zlweicoder @dengyakui @WalkerLu  @liminany @CadenGjy 

**一组：** 

 - [x]  作为船屋老板，我希望可以把船屋品牌的故事分享给大家，增加品牌认可度 业务系统  #112
 - [x]  作为测试人员，需要系统能够支持Jmeter接口测试，以便于快速完成繁琐工作，大幅提升工作效率，避免重复工作。 #34
 - [ ]  作为开发人员，我希望项目可以是基于SpringCloud微服务架构，以便参考学习  （延伸任务）（根据团队的能力自己决定实现哪一块，配置中心、API网关、服务发现、监控等）#108

**二组：**

 - [ ]  作为开发人员，我希望项目可以是基于SpringCloud微服务架构，以便参考学习 （延伸任务）（根据团队的能力自己决定实现哪一块，配置中心、API网关、服务发现、监控等）#108
 - [x]  作为船屋老板，我希望船屋站点可以支持加盟申请，以便我可以拓展业务 业务系统
延展目标：SpringCloud全组建搭建 #111 

**三组：**

 - [x]  作为移动团队，我希望可以有APP程序（MVP版本），以便配置支撑APP的流水线 #82  
 - [ ]   作为移动团队，我希望看到APP流水线的搭建过程，以便应用到实际项目上  #107
 - [ ]  作为客人，我希望可以通过搜索菜品名称，来选择自己喜爱的菜肴 业务系统  #113

**四组：**

- [x] 作为船屋老板，我希望船屋站点可以在后台进行菜品的管理，可以长传图片 业务系统 #110
- [x] 作为测试人员，我希望Jenkins集成自动化UI测试，以便于提高UI测试效率，重复利用测试用例 #37 
- [x] 作为运维人员，我希望能支持github action等其它CI方式，以方便我们做各类适配丰富案例 #104 

暂未选择：

- [ ] 做为运维人员，我希望在Jenkins流水线中使用传统模式部署（非容器话方式）#65 
- [ ] 作为客人，我希望船屋站点可以支持用户登录注册，以便后续可以在线点餐 业务系统 #109 

维护团队：

- [x] 作为PR提交者，我不想每次对Jenkinsfile等配置文件每次提交PR时都修改 #133
- [x] boathouse_statistics-service-worker_1 这个服务占用系统资源太大 #132
