### ISSUE TITLE
迭代计划 - 2020年3月 - 迭代三（3.10 - 3.23）

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#164]
整体目标: 

PO: @pipin @elegant1998 @brother-dong @ups216 
维护团队： @zhouwenyang @zlweicoder @dengyakui @WalkerLu  @liminany @CadenGjy 

General：

 - k8s环境搭建部署（持续学习、持续改进、持续完善）
 - 单元测试（持续学习、持续改进、持续完善）
 - 接口测试（持续学习、持续改进、持续完善）
 - UI测试（持续学习、持续改进、持续完善）

**一组：** 

- [ ] #112 作为船屋老板，我希望可以把船屋品牌的故事分享给大家，增加品牌认可度  - 前后端集成
- [ ] #122 作为运维人员，我希望可以在Kubernetes生产环境中实现mysql集群搭建
- [x] #114 作为客人，我希望通过船屋网站进行下单，以便可以让我享受地道的苏格兰美食 

**二组：**

- [x] #109 作为客人，我希望船屋站点可以支持用户登录注册，以便后续可以在线点餐 
- [x] #167 作为客人，我希望船屋站点可以支持添加食物到购物车的功能 
- [x] #162 作为运维人员，我希望docker-compse以及kube yaml文件不要hardcode tag 

**三组：**

- [ ] #113  作为客人，我希望可以通过搜索菜品名称，来选择自己喜爱的菜肴 - 代码合并
- [x] #154 作为代码库管理人员，我希有前端开发详细规范，以减少合并冲突 
- [x] #153 作为代码库管理人员，我希望api服务开发详细规范，以减少合并冲突。 
- [ ] #166 作为客人，我希望船屋APP 可以显示菜品列表 
- [ ] #107 作为移动团队，我希望看到APP流水线的搭建过程，以便应用到实际项目上 

**四组：**

- [x] #148 作为运维我想在github action中可以实现部署验证的功能，不用依赖团队的Jenkins，实现快速交付 
- [x] #155 作为开发人员，我希望docker-compose-template.yaml文件不要hardcode 组织 
- [ ] #125 作为运维人员我希望kubernetes集群有对应的监控方案，确保可以对集群整体的监控 
- [x] #165 作为客人，我希望船屋APP 可以 支持登录注册 

**未领取：**

业务系统：

-  [ ] #169 作为客人，我希望船屋APP可以支持添加食物到购物车的功能 
-  [ ] #168 作为用户，我希望APP可以有定位服务，能定位到我的位置方便外卖点餐 

工具链：

- [ ] #65  做为运维人员，我希望在Jenkins流水线中使用传统模式部署（非容器化方式）
